version = 1
exclude_patterns = []
test_patterns = []

[[analyzers]]
  name = "ansible"
  enabled = true

[[analyzers]]
  name = "cfn-lint"
  enabled = true

[[analyzers]]
  name = "csharp"
  enabled = true

[[analyzers]]
  name = "dart-analyze"
  enabled = true

[[analyzers]]
  name = "docker"
  enabled = true

  [analyzers.meta]
    dockerfile_paths = ""

[[analyzers]]
  name = "go"
  enabled = true

  [analyzers.meta]
    dependencies_vendored = "true"
    import_root = ""

[[analyzers]]
  name = "java"
  enabled = true

  [analyzers.meta]
    runtime_version = "8"

[[analyzers]]
  name = "javascript"
  enabled = true

  [analyzers.meta]
    environment = "nodejs"
    plugins = "react"

[[analyzers]]
  name = "kotlin"
  enabled = true

  [analyzers.meta]
    language_version = "1.0"
    runtime_version = "1.8"

[[analyzers]]
  name = "kube-linter"
  enabled = true

[[analyzers]]
  name = "php"
  enabled = true

  [analyzers.meta]
    bootstrap_files = ""

[[analyzers]]
  name = "python"
  enabled = true

  [analyzers.meta]
    runtime_version = "3.x.x"

[[analyzers]]
  name = "ruby"
  enabled = true

[[analyzers]]
  name = "rust"
  enabled = true

  [analyzers.meta]
    msrv = ""

[[analyzers]]
  name = "scala"
  enabled = true

[[analyzers]]
  name = "secrets"
  enabled = true

[[analyzers]]
  name = "shell"
  enabled = true

[[analyzers]]
  name = "slither"
  enabled = true

[[analyzers]]
  name = "solhint"
  enabled = true

[[analyzers]]
  name = "sql"
  enabled = true

[[analyzers]]
  name = "swift"
  enabled = true

[[analyzers]]
  name = "terraform"
  enabled = true

[[analyzers]]
  name = "test-coverage"
  enabled = true

[[transformers]]
  name = "black"
  enabled = true

[[transformers]]
  name = "prettier"
  enabled = true

[[transformers]]
  name = "autopep8"
  enabled = true
