name: Automated Test Suite
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_MODE: "1"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run backend tests
        run: |
          TEST_MODE=1 pytest backend/test_*.py && TEST_MODE=1 PYTHONPATH=. pytest tests/test_backtest.py
      - name: Run frontend tests
        run: |
          cd frontend
          npx vitest run src/__tests__/GridForm.test.jsx
          npx vitest run src/GridForm.test.tsx
          npx vitest run src/__tests__/GridForm.accessibility.test.jsx
          npx vitest run src/__tests__/GridForm.realapi.test.jsx
          npx vitest run src/__tests__/GridForm.crosslayer.test.jsx
          npx vitest run src/__tests__/GridForm.accessibility.axe.test.jsx
